#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2008,
#               Markus Leist <leist@ikom-online.de>
# See also LICENSE.txt or http://www.ict-ok.org/LICENSE
# This file is part of ict-ok.org.
#
# $Id: interfaces.py 145 2008-02-15 20:41:04Z markusleist $
#
# pylint: disable-msg=
#
"""Startscript for cron runner
"""

__version__ = "$Id: host.py 174 2008-03-05 17:51:14Z markusleist $"

from org.ict_ok.agents.cron.runner import runner

if __name__ == '__main__':
    runner(appname=None, configfile='./zope.conf')
