#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2008,
#               Markus Leist <leist@ikom-online.de>
# See also LICENSE.txt or http://www.ict-ok.org/LICENSE
# This file is part of ict-ok.org.
#
# $Id$
#
# pylint: disable-msg=
#
"""Startscript for cron runner
"""

#
# TODO: abs. path are evil hack - have to use buildout
#

__version__ = "$Id$"

import sys
import zdaemon.zdctl

if __name__ == '__main__':
    zdaemon.zdctl.main([
        '-C', '/home/markus/Projekte/ict_ok.org/inst/lib/python/org/ict_ok/agents/cron/zdaemon.conf',
        ]+sys.argv[1:]
        )
