#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2008,
#               Markus Leist <leist@ikom-online.de>
# See also LICENSE.txt or http://www.ict-ok.org/LICENSE
# This file is part of ict-ok.org.
#
# $Id$
#
# pylint: disable-msg=
#
"""Startscript for nagios ndo runner
"""

#
# TODO: abs. path are evil hack - have to use buildout
#

__version__ = "$Id$"

import sys
sys.path[0:0] = [
  '/opt/markus/ICT-OKs/ict-ok_10.04/src',
  '/opt/markus/ICT-OKs/ict-ok_10.04/py_eggs/zdaemon-2.0.4-py2.6.egg',
  '/opt/markus/ICT-OKs/ict-ok_10.04/py_eggs/setuptools-0.6c11-py2.6.egg',
  '/opt/markus/ICT-OKs/ict-ok_10.04/py_eggs/ZConfig-2.8.0-py2.6.egg',
  '/opt/markus/ICT-OKs/ict-ok_10.04/py_eggs/zc.zope3recipes-0.11.0-py2.6.egg',
  ]

import zdaemon.zdctl

if __name__ == '__main__':
    zdaemon.zdctl.main([
        '-C', '/opt/markus/ICT-OKs/ict-ok_10.04/src/org/ict_ok/agents/ndoutils/zdaemon.conf',
        ]+sys.argv[1:]
        )
