#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2008,
#               Markus Leist <leist@ikom-online.de>
# See also LICENSE.txt or http://www.ict-ok.org/LICENSE
# This file is part of ict-ok.org.
#
# $Id$
#
# pylint: disable-msg=
#
"""Startscript for nagios ndo runner
"""

__version__ = "$Id$"

from org.ict_ok.agents.ndoutils.runner import runner

if __name__ == '__main__':
    runner(appname=None, configfile='./zope.conf')
